### PR TITLE
Add support other compression methods for squashfs

### LINKED ISSUE #13: Add support for pluggable compression/decompression for Squashfs?
Hey, firstly I would like to say that I greatly appreciate the effort to maintain this fork, keep up the good work! ☺️ 

I have been trying to use squashfs but discovered that it only supports Zlib compression/decompression. Not surprising because that's the only supported compression library that is builtin in .NET! 😅 

As there is quite a zoo of compression libs for other formats with various versions - managed and native wrappers, I have made a small prototype in a branch to add support for pluggable compression/decompression. The changes are very minimal, just a few lines of code here and there.

Would you be open for this feature If I create a PR?

### PR DESCRIPTION
**Pull request by xoofx**
Fixes #13

Somes notes about this PR:

- I have added the usage of https://github.com/Sergio0694/PolySharp to allow to use more recent language features. It doesn't add runtime dependencies but allows to use e.g init properties.
- I have used `Func<X,Y>` for resolving compressors/streams to simplify the code and avoid polluting the namespace with delegates. If you prefer delegates for consistency of the codebase, let me know and I can change it.
- I have kept the set of 0xDA (Best compression) when compressing with Zlib. It caused me some trouble because I forgot to remove it for the other compression. 😅 But not sure why it is there.

### CODE REVIEW

**Comment by xoofx** [comment]
Testing with unsquashfs and I'm getting an error. It seems that I need to output a compressor options structure to the archive. Will dig into it.

**Comment by xoofx** [comment]
Ok, so, it seems that it will require a bit more work than expected, as it requires to handle compression options (e.g for Lz4 [here](https://github.com/plougher/squashfs-tools/blob/4d6b9605f462a6e8e64aed5371910ba63363756e/squashfs-tools/lz4_wrapper.c#L135-L169)), though I thought that it was requiring to set a flags in the super block, but it seems that it does try to extract the options anyway ([here](https://github.com/plougher/squashfs-tools/blob/4d6b9605f462a6e8e64aed5371910ba63363756e/squashfs-tools/read_fs.c#L640-L670))

It will take a bit more time to check all these details 😅

**Comment by Olof-Lagerkvist** [comment]
Thanks a lot for working on this!

**Comment by xoofx** [comment]
Ok, I got it working. Now I'm going to have to cleanup and optimize a bit more things.

I have one question: I need to add the implementation of a e.g `FastMemoryStream` derived from `System.IO.Stream` that I would like to use from the SquashFs project. Where would you prefer such implementation to live?
- In `DiscUtils.Streams`? But it creates a new dependency to this project from squashfs...
- In `DiscUtils.Core` using or not the namespace `DiscUtils.Streams`?
- In `DiscUtils.SquashFs`?

**Comment by xoofx** [comment]
Nevermind, I can actually workaround it with a standard `MemoryStream`, let's see!

**Comment by xoofx** [comment]
Last commit should fix remaining issues. I have slightly optimized things related to usage of MemoryStream to reuse a shared one in the builder.

I have also successfully tested on a Linux box:
- Mounting a squashfs archive created with DiscUtils with both zlib and lz4 compression
- Using `unsquashfs` tools to stat/list the content of the archive

**Comment by Olof-Lagerkvist** [comment]
> Ok, I got it working. Now I'm going to have to cleanup and optimize a bit more things.
> 
> I have one question: I need to add the implementation of a e.g `FastMemoryStream` derived from `System.IO.Stream` that I would like to use from the SquashFs project. Where would you prefer such implementation to live?
> - In `DiscUtils.Streams`? But it creates a new dependency to this project from squashfs...
> - In `DiscUtils.Core` using or not the namespace `DiscUtils.Streams`?
> - In `DiscUtils.SquashFs`?

New Stream derived classes and other I/O related general purpose classes should be in DiscUtils.Streams. It would not create a new dependency, all DiscUtils projects use DiscUtils.Streams already. Some do not reference it directly though because it is brought in automatically by the dependency on DiscUtils.Core which uses DiscUtils.Streams.

**Comment by Olof-Lagerkvist** [comment]
Great! Thanks a lot for your contribution! I'll take a look in the next few days!

**Comment by Olof-Lagerkvist** [comment]
I have had some quick looks at the code. It looks good for most parts, but just a couple of things:

* Looking at the diff for `.gitignore`, I am fine with the added things, but not the removed things. We need to keep things like `launchsettings.json` and certain build artifacts out of the repository.

* Test project, I would like to still support .NET Framework 4.6. This requires version 1.2.16 of `K4os.Compression.LZ4` that you added. This requires some changes to the project file to bring in different versions for different target frameworks.

I can branch the pull request and make some changes that I have in mind!

**Comment by Olof-Lagerkvist** [comment]
I created a new branch for working on this until I merge it into master branch.

**Comment by xoofx** [comment]
Thank you for taking this PR, looking forward for the final merge! ☺️

**Pull request merged**
