### PR TITLE
Adding progress tracking for files and directories

### PR DESCRIPTION
**Pull request by DevX-Cipher**
This pull request introduces progress tracking for both files and directories during operations.

Added UpdateProgress(_files.Count, _files.Count + _dirs.Count); to update progress during operations.
Ensured accurate progress calculation for both files and directories.

The addition of progress tracking enhances user experience by providing real-time feedback during operations. Users will now have better visibility into the progress of file and directory operations, improving overall usability and user satisfaction.

### CODE REVIEW

**Comment by Olof-Lagerkvist** [comment]
Thanks for your pull request!

Just a question, what is your idea behind "currentProgress" and "totalItems"? From what I can see, they are both values representing current progress, but the first is number of files and the other one is number of files + number of directories?

**Comment by DevX-Cipher** [comment]
users can get a more detailed view of the progress of the operation. For instance, if "currentProgress" is 50 and "totalItems" is 100

**Comment by Olof-Lagerkvist** [comment]
Okay. To make things more clear and easy to understand, I think I'll rename them "totalFiles" and "totalItems" instead. Otherwise it might be mistaken as referring to current number of items and total number of items about to be added to the file system.

**Comment by Olof-Lagerkvist** [comment]
Or maybe "currentFilesCount" and "currentItemsCount". That should make it clear.

**Comment by DevX-Cipher** [comment]
yes that would work

**Comment by DevX-Cipher** [comment]
@LTRData does this one help now hoepfully

**Comment by Olof-Lagerkvist** [comment]
I changed it a bit a introduced a more generic event for progress updates in base interface `IFileSystemBuilder`.
https://github.com/LTRData/DiscUtils/pull/11/commits/e01584d87c26a3de8935ac88e3ac5b7a2addf77f

Merged into main branch now.

**Comment by DevX-Cipher** [comment]
should i close this now since you didn't merge this

**Comment by Olof-Lagerkvist** [comment]
> should i close this now since you didn't merge this

Yes, we can close this.
Referring to this one instead: https://github.com/LTRData/DiscUtils/pull/11

**Comment by DevX-Cipher** [comment]
ok alo increasing the speed as well I have done this but I'm sure there is a better way

**Pull request closed without merging**
