### PR TITLE
Add support for writing long file name to FAT

### LINKED ISSUE #15: Issues with long file names in FAT
First of all, thank you for maintaining the project.

I want to copy some files inside a FAT image, in read I see the long file names correctly.
When I go to write, however, it seems to fail to go beyond the 8.3 format, forcing the name to be uppercase (except the extension).

Below is an example of how I am operating, and how I then see the file by opening the image from 7zip:

```
string diskDump = "EFIESP.bin";
string sourcePath = @"DATA\developermenu.efi";
string destPath = @"Windows\System32\BOOT\developermenu.efi";

using (FileStream fs = File.Open(diskDump, FileMode.Open))
{
    if (!FatFileSystem.Detect(fs))
    {
        Console.WriteLine("Error: Dump is not formatted with FAT filesystem.");
        return;
    }
    using (FatFileSystem disk = new FatFileSystem(fs))
    {
        using (Stream s = disk.OpenFile(destPath, FileMode.Create))
        {
            using (var fileStream = File.Open(sourcePath, FileMode.Open))
            {
                fileStream.CopyTo(s);
            }
        }
    }
    Console.WriteLine("File copied.");
}
```
image

I don't know if I did something wrong. By any chance are long names supported only in read and not in write? Thank you

### PR DESCRIPTION
**Pull request by xoofx**
Fixes #15

Opening this PR early on as a draft version with a first version for adding full support for long file names (LFN). It should not be merged yet! 😅 

The tests are passing ✅, but I will have to add a lot more tests and there are plenty of corner cases that will/might not work yet as expected (e.g changing a short name)

The main change is `FileName` class converted to a `FatFileName` struct. This new struct covers the encoding/decoding of LFN+SFN. 

Another - smaller - change is in Directory for using more acceleration dictionaries + a free entry acceleration table (in order to handle LFN entries being deleted).

It's gonna take a few more days to polish and make it solid. 🤞

### CODE REVIEW

**Comment by xoofx** [comment]
Another aspect are short name collisions, while they should be correctly handled at the `FatFileName` level, there is more work to do in `Directory` to support them correctly.

**Comment by xoofx** [comment]
One nice finding discovery that I was able to implement is from http://tomgalvin.uk/blog/gen/2015/06/09/filenames/ where he gives details about how short name hashing for handling collisions is actually implemented in Windows NT+

So the `FatFileName` is implementing it and it shows similar result to what you could get on a real FAT filesystem on Windows.

**Comment by xoofx** [comment]
Also, the full validation of this PR will require to check that generated FAT disk do work when mounting them on Linux or from a USB stick.

**Comment by Olof-Lagerkvist** [comment]
> One nice finding discovery that I was able to implement is from http://tomgalvin.uk/blog/gen/2015/06/09/filenames/ where he gives details about how short name hashing for handling collisions is actually implemented in Windows NT+
> 
> So the `FatFileName` is implementing it and it shows similar result to what you could get on a real FAT filesystem on Windows.

There is really no need for such reverse engineering. Windows NT FAT driver is open source since at least 20 years. The logic for short names is mostly here: 
https://github.com/microsoft/Windows-driver-samples/blob/main/filesys/fastfat/dirsup.c

**Comment by xoofx** [comment]
> The logic for short names is mostly here:

Not really 🙂 The function used to generate 8.3 name is behind the function `RtlGenerate8dot3Name` which is not part of this repository but is actually in ntdll.dll (that's what was the goal of the investigation in the post above)

**Comment by Olof-Lagerkvist** [comment]
> > The logic for short names is mostly here:
> 
> Not really 🙂 The function used to generate 8.3 name is behind the function `RtlGenerate8dot3Name` which is not part of this repository but is actually in ntdll.dll (that's what was the goal of the investigation in the post above)

Ah, I misunderstood what the reverse engineering was about then! Sorry!

**Comment by xoofx** [comment]
So, I have added several tests, it should have improved coverage on FAT from 70% to 77%. It is far from perfect, the original project is still missing some stuffs here and there, but it's getting better with these tests hopefully. 🤞 

I made the PR ready for review to give it more visibility.

Tomorrow early morning I will spend some time to verify that produced FAT filesystem with LFN are working well when mounted from a real disk.

**Comment by Olof-Lagerkvist** [comment]
I just did some experiments with your code. It looks good, I think.

I tried to remove your `unsafe` keywords and it was pretty easy to get it to work anyway. Just had to add another overload to `EncodingExtensions.GetChars` that extended `Encoding` in the same way as the existing one extends `Decoder`, as well as some other minor tweaks. I think I'll add these changes to a branch I created before merging it.

**Comment by xoofx** [comment]
> Tomorrow early morning I will spend some time to verify that produced FAT filesystem with LFN are working well when mounted from a real disk.

I was able to test it on a real disk and seems to work just fine, so this should be good to go!

**Comment by Olof-Lagerkvist** [comment]
Really nice! Thanks a lot for your contribution! 👍

**Comment by Olof-Lagerkvist** [comment]
Looks like tests fail on Linux. Maybe there is a hard coded `\` as path separator somewhere. I can check!

**Comment by Olof-Lagerkvist** [comment]
Everything fixed, merged and new NuGet packages are right now uploading.

Again, thanks a lot for your contributions!

**Pull request merged**
